# Site Settings
title: Flushing Reality
email: domattthings@gmail.com
description: All about video game bathrooms
# baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://flushingreality.com" # the base hostname & protocol for your site
google_analytics: "UA-110856410-11"

authors:
  - name: Matt Lewis
    Position: Cofounder, Web Stuff, & Systems Administrator
    description: Matt likes video games, but usually never has time to play them. He's usually found at the local bar.
    image: /assets/img/matt.jpg
    homepage: https://mattmatters.io
    github: mattmatters
    twitter: dancinpolkabear
  - name: Tyler Cifelli
    Position: Cofounder, web stuff, and graphic design
    description: Tyler has a degree in game design and is actively involved in the scene.  He's probably the only one actually qualified on the site.
    github: tylercifelli
    image: /assets/img/tyler.jpg
  - name: Chelby Sharpe
    Position: Cofounder & Writer
    description: Chelby claims to like video games, we are still waiting on proof though
    image: /assets/img/chelby.jpg
    twitter: wolfychaaan

# User Settings
username: matt
user_description: Some text about you.
disqus_username: flushingreality-com

# Social Media
# Remove the item if you don't need it
github_username: github_username
facebook_username: facebook_username
twitter_username: twitter_username
instagram_username: instagram_username
# linkedin_username: linkedin_username
# medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
