# Site Settings
title: Flushing Reality
email: domattthings@gmail.com
description: All about video game bathrooms
# baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://flushingreality.com" # the base hostname & protocol for your site
google_analytics: "UA-110856410-11"

authors:
  matt:
    name: Matt Lewis
    github: mattmatters
  chelby:
    name: Chelby Sharpe
  tyler:
    name: Tyler Cifelli

# User Settings
username: Flushing Reality
user_description: Some text about you.
disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it
github_username: github_username
facebook_username: facebook_username
twitter_username: twitter_username
instagram_username: instagram_username
linkedin_username: linkedin_username
medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
